# Generated by Django 5.0 on 2023-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='messages',
        ),
    ]
