# Generated by Django 5.0 on 2024-01-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_usermessage_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackData',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
