# Generated by Django 5.0 on 2024-01-02 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='timestap',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
